### ISSUE TITLE
Handle case where user does not have access to collection

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#142]
```
artx-market-app-1       | Error processing request: TypeError: Cannot read properties of undefined (reading 'asset')
artx-market-app-1       |     at Object.getCollection (/app/xidb.js:885:54)
artx-market-app-1       |     at /app/server.js:810:29
artx-market-app-1       |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       |     at next (/app/node_modules/express/lib/router/route.js:144:13)
artx-market-app-1       |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
artx-market-app-1       |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       |     at /app/node_modules/express/lib/router/index.js:284:15
artx-market-app-1       |     at param (/app/node_modules/express/lib/router/index.js:365:14)
artx-market-app-1       |     at param (/app/node_modules/express/lib/router/index.js:376:14)
artx-market-app-1       |     at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
artx-market-app-1       | GET /api/v1/collections/0e5052c9-7c9e-49e3-a873-a7953deebe01 500 24.182 ms - 59
```

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/afa411391164865efce50fd55a935ce871bc79f5
