### ISSUE TITLE
Improve handling for unminted nft

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#155]
```

artx-market-app-1       | Error: TypeError: Cannot read properties of null (reading 'nft')
artx-market-app-1       |     at saveNft (/app/xidb.js:942:30)
artx-market-app-1       |     at Object.getNft (/app/xidb.js:992:16)
artx-market-app-1       |     at /app/server.js:437:26
artx-market-app-1       |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       |     at next (/app/node_modules/express/lib/router/route.js:144:13)
artx-market-app-1       |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
artx-market-app-1       |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       |     at /app/node_modules/express/lib/router/index.js:284:15
artx-market-app-1       |     at param (/app/node_modules/express/lib/router/index.js:365:14)
artx-market-app-1       |     at param (/app/node_modules/express/lib/router/index.js:376:14)
artx-market-app-1       | GET /api/v1/nft/3044a845-8e94-47e1-9846-73578bf0c81d 404 3.173 ms - 27
```

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/452d1ffaeccde41deb961c5cb6c0805906cb0fc4
