### ISSUE TITLE
Must include https:// in link

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#178]

**Comment by macterra** [comment]
bad link (e.g. google.com) raises server error

```
artx-market-app-1       | 2023-11-17T16:55:33.613908811Z Error fetching profile data: TypeError: Cannot set properties of null (setting 'collections')
artx-market-app-1       | 2023-11-17T16:55:33.613942591Z     at Object.getAgentAndCollections (/app/xidb.js:364:27)
artx-market-app-1       | 2023-11-17T16:55:33.613947730Z     at /app/server.js:812:32
artx-market-app-1       | 2023-11-17T16:55:33.613951985Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       | 2023-11-17T16:55:33.613956052Z     at next (/app/node_modules/express/lib/router/route.js:144:13)
artx-market-app-1       | 2023-11-17T16:55:33.613959994Z     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
artx-market-app-1       | 2023-11-17T16:55:33.613964008Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       | 2023-11-17T16:55:33.613968060Z     at /app/node_modules/express/lib/router/index.js:284:15
artx-market-app-1       | 2023-11-17T16:55:33.613972051Z     at param (/app/node_modules/express/lib/router/index.js:365:14)
artx-market-app-1       | 2023-11-17T16:55:33.613976229Z     at param (/app/node_modules/express/lib/router/index.js:376:14)
artx-market-app-1       | 2023-11-17T16:55:33.613980160Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
artx-market-app-1       | 2023-11-17T16:55:33.614771606Z GET /api/v1/profile/google.com 500 5.186 ms - 41
```

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/8e1075f55cc2333f591bfbc8bc0f6d03883389fb

**Comment by Pennycrumb** [comment]
error occur for certain urls on mobile
![Screenshot_20231120_235254_Chrome](https://github.com/macterra/artx-market/assets/147219681/d37b37f2-d91b-4939-b937-58d0882dffe9)
![Screenshot_20231122_233645_Chrome](https://github.com/macterra/artx-market/assets/147219681/facb3892-7601-492a-8d2d-436f3095a0ca)
![Screenshot_20231122_233700_Chrome](https://github.com/macterra/artx-market/assets/147219681/462932bd-cf40-4471-9c5e-d1383449ca7c)

**Comment by macterra** [comment]
Those are all correct. https://lucifer.com, https://monkeybat.com and https://www.monkeybat.com are invalid.

http://lucifer.com, http://monkeybat.com and http://www.monkeybat.com (without the s) are valid and will work if entered.

**Comment by macterra** [comment]
Agreed to remove https:// from text prompt

**Comment by Pennycrumb** [comment]
Tested
