### ISSUE TITLE
Blank page when viewing collection while unauthorized

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#185]
```
artx-market-app-1       | 2023-11-17T19:56:35.450435739Z Error processing request: TypeError: Cannot read properties of undefined (reading 'collection')
artx-market-app-1       | 2023-11-17T19:56:35.450470117Z     at /app/server.js:972:20
artx-market-app-1       | 2023-11-17T19:56:35.450475479Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       | 2023-11-17T19:56:35.450479905Z     at next (/app/node_modules/express/lib/router/route.js:144:13)
artx-market-app-1       | 2023-11-17T19:56:35.450484252Z     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
artx-market-app-1       | 2023-11-17T19:56:35.450488301Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
artx-market-app-1       | 2023-11-17T19:56:35.450492283Z     at /app/node_modules/express/lib/router/index.js:284:15
artx-market-app-1       | 2023-11-17T19:56:35.450496225Z     at param (/app/node_modules/express/lib/router/index.js:365:14)
artx-market-app-1       | 2023-11-17T19:56:35.450500121Z     at param (/app/node_modules/express/lib/router/index.js:376:14)
artx-market-app-1       | 2023-11-17T19:56:35.450504017Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:421:3)
artx-market-app-1       | 2023-11-17T19:56:35.450507953Z     at next (/app/node_modules/express/lib/router/index.js:280:10)
artx-market-app-1       | 2023-11-17T19:56:35.451765422Z GET /api/v1/collections/20c2491d-55d4-427f-9cea-e1b81d5db458 500 14.795 ms - 59
```

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/76a00234476543d4c0d683d8b7b890e5817d46c0
