### ISSUE TITLE
Fail to mint

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#50]
Reported by Sat

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
TokenMinter.js:158 Error minting: ap
(anonymous) @ TokenMinter.js:158
```

**Comment by santyr** [comment]
Error arose while minting values entered 2% royalty 9 editions.  Failed twice after successful payments.

**Comment by macterra** [comment]
Fixed one bug, uncovered another:

```

artx-market-app-1       | Error: TypeError: fetch failed
artx-market-app-1       |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
artx-market-app-1       |     at async createToken (/app/xidb.js:765:22)
artx-market-app-1       |     at async /app/server.js:417:5 {
artx-market-app-1       |   cause: RequestContentLengthMismatchError: Request body length does not match content-length header
artx-market-app-1       |       at AsyncWriter.end (node:internal/deps/undici/undici:10355:19)
artx-market-app-1       |       at writeIterable (node:internal/deps/undici/undici:10263:16) {
artx-market-app-1       |     code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
artx-market-app-1       |   }
artx-market-app-1       | }
artx-market-app-1       | POST /api/v1/asset/84ff323d-1877-4877-b14c-87f16f2f907c/mint 500 107.739 ms - 19
```

**Comment by santyr** [comment]
Was abvle to mint without error this morning. ;)
