### ISSUE TITLE
walletofsatoshi limits

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#54]
Error when paying out to walletofsatoshi address:

```
Error: The comment length must be 32 characters or fewer
    at /home/david/dev/artx-market/node_modules/lnurl-pay/dist/cjs/request-invoice.js:25:31
    at step (/home/david/dev/artx-market/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/david/dev/artx-market/node_modules/tslib/tslib.js:176:57)
    at /home/david/dev/artx-market/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/david/dev/artx-market/node_modules/tslib/tslib.js:165:16)
    at requestInvoiceWithServiceParams (/home/david/dev/artx-market/node_modules/lnurl-pay/dist/cjs/request-invoice.js:9:20)
    at /home/david/dev/artx-market/node_modules/lnurl-pay/dist/cjs/request-invoice.js:81:87
    at step (/home/david/dev/artx-market/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/david/dev/artx-market/node_modules/tslib/tslib.js:176:57)
```

**Comment by santyr** [comment]
The commentAllowed value can be used to get the max characters for a lightning address. 

Use to get all needed info about an address - https://lnb.bolverker.com/docs#/Core/api_lnurlscan_api_v1_lnurlscan__code__get

Response:

{
  "domain": "lightning-goats.com",
  "tag": "payRequest",
  "callback": "https://lnb.bolverker.com/lnurlp/api/v1/lnurl/cb/lnaddr/Uyg3Jz",
  "minSendable": 1000,
  "maxSendable": 100000000000,
  "metadata": "[[\"text/plain\", \"Payment to herd\"], [\"text/identifier\", \"herd@lnb.bolverker.com\"]]",
  "commentAllowed": 250,
  "allowsNostr": true,
  "nostrPubkey": "2ef28aa93cf9a1bb4918de7319e040f8a5eba319a2151d92cb01a96268fe1b4e",
  "kind": "pay",
  "fixed": false,
  "description_hash": "b19731185b536ba3b4ede978ac5f1c28bbb60d0384b0499935218bad1b467c6b",
  "description": "Payment to herd",
  "targetUser": "herd@lnb.bolverker.com"
}

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/a1146a138a8d38763682d5a890bef790b0745c7f
