### ISSUE TITLE
Error fetching profile data: TypeError: Cannot read properties of null (reading 'collections')

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#55]
On viewing another's collection

```
artx-market-app-1       | Error fetching profile data: TypeError: Cannot read properties of null (reading 'collections')
artx-market-app-1       |     at getAgentAndCollections (/app/xidb.js:607:42)
artx-market-app-1       |     at async /app/server.js:630:23
```

Doesn't seem to affect the UI

**Comment by macterra** [comment]
```
artx-market-app-1       | Error fetching profile data: TypeError: Cannot read properties of null (reading 'collections')
artx-market-app-1       |     at getAgentAndCollections (/app/xidb.js:664:19)
artx-market-app-1       |     at async /app/server.js:697:23
artx-market-app-1       | GET /api/v1/profile/null 500 1.856 ms - 41
```

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/51a7d8d3175badbd1897760003c853e8a1072970
