### ISSUE TITLE
Error reading metadata: TypeError: Cannot read properties of null (reading 'asset')

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#59]
```
artx-market-app-1       | Error reading metadata: TypeError: Cannot read properties of null (reading 'asset')
artx-market-app-1       |     at isOwner (/app/xidb.js:781:18)
artx-market-app-1       |     at /app/server.js:465:35
artx-market-app-1       | GET /api/v1/asset/9f85726c-96be-49e5-b6dc-d40c998645cc 404 1.921 ms - 29
```

https://artx.market/asset/f6932ce2-a001-450f-8565-c6dd3cf31212 (token tab)

**Comment by macterra** [comment]
Possibly fixed in https://github.com/macterra/artx-market/commit/d556679479f2cba201c94cbab7c536af8297aecd

**Comment by macterra** [comment]
Possible fix in https://github.com/macterra/artx-market/commit/509d38bd29b059f19a1e9ac2f5adc24bc7ea76d9
